[workspace]
resolver = "1"
default-members = [
    "margarine",
]

members = [
    "margarine",
    "margarine/common",
    "margarine/common/derive",
    "margarine/lexer",
    "margarine/parser",
    "margarine/sema",
    "margarine/errors",
    "scripts/fuzz"
]

[profile.release]
debug = true
lto = false
opt-level = 3
codegen-units = 1
split-debuginfo = "packed"

[profile.dist]
inherits = "release"
debug = false
strip = "symbols"
