[package]
name = "common"
version = "0.1.0"
edition = "2021"

[features]
fuzzer = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sti = { path = "../../vendor/sti" }
colourful = { git = "https://github.com/rookieCookies/colourful" }
derive = { path = "./derive" }
